services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT_LOCAL}"
  
  # redis:
  #   image: redis:7.4
  #   container_name: redis_server
  #   ports:
  #     - "${REDIS_PORT}:${REDIS_PORT_LOCAL}"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  
  # redisinsight:
  #   image: redis/redisinsight:latest
  #   container_name: redisinsight
  #   ports:
  #     - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT_LOCAL}"
  #   restart: unless-stopped
  #   depends_on:
  #     - redis

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT_LOCAL}"

# volumes:
#   redis_data: